### ISSUE TITLE
Uncaught exception 'Exception' with message 'String could not be parsed as XML'

### ISSUE THREAD

**Issue by hervethouzard** [asimlqt/php-google-spreadsheet-client#24]
Hello,

I get the folowing error :
<pre>
Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetFeed.php:45
Stack trace:
#0 /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetFeed.php(45): SimpleXMLElement->__construct('')
#1 /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php(39): Google/Spreadsheet/SpreadsheetFeed->__construct(false)
#2 /index.php(33): Google/Spreadsheet/SpreadsheetService->getSpreadsheets()
#3 {main}
  thrown in /vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetFeed.php on line 45
</pre>

When using this code :
<pre>
ini_set('display_errors', 'on');
error_reporting(E_ALL);
require 'vendor/autoload.php';

use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;

$client = new Google_Client();
$client->setApplicationName('MyProjet1');
$client->setClientId('01234567890-dskjhkdshfvjkdvkhdskjhvkjfdh.apps.googleusercontent.com');

$cred = new Google_Auth_AssertionCredentials(
    '01234567890-sdkjchjdkfhvlkdlsncjdhvcddsfvd@developer.gserviceaccount.com',
    array('https://spreadsheets.google.com/feeds'),
    file_get_contents('myfile.p12')
);

$client->setAssertionCredentials($cred);

if($client->isAccessTokenExpired()) {
    $client->getAuth()->refreshTokenWithAssertion($cred);
}

$obj_token  = json_decode($client->getAccessToken());
$accessToken = $obj_token->access_token;

$serviceRequest = new DefaultServiceRequest($accessToken);
ServiceRequestFactory::setInstance($serviceRequest);

$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$spreadsheetFeed = $spreadsheetService->getSpreadsheets();
print_r($spreadsheetFeed);
</pre>

Apparently there's nothing in $xml:
<code>
$this->xml = new SimpleXMLElement($xml);
</code>

Could you help me please ?

Bye,
Hervé

**Comment by berendj** [comment]
I am having this same issue. I have been narrowing it down to this (using the code-examples found everywhere ):
The serviceRequest i get from DefaultServiceRequest contains a blank header. I do not know if that is correct. After using the serviceRequest in ServiceRequestFactory::setInstance($serviceRequest) and retrieving the spreadsheetService I get an Object with value 'Google\Spreadsheet\SpreadsheetService' but which is completely empty.

Hope this can be of help to anyone trying to solve this problem

**Comment by tamcy** [comment]
For the issue of `curl_exec()` returning `false`, it can be either worked around by setting `CURLOPT_SSL_VERIFYPEER` to false as mentioned by @garethwhittaker, or follow the steps provided by http://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/ :

1. Download the CA root certificate (cacert.pem) from http://curl.haxx.se/docs/caextract.html
2. Add the following line in your php.ini (change the path to where you cacert.pem):
```
curl.cainfo=c:\php\cacert.pem
```
Restart your web server and profit.

**Comment by thiha-min-thant-20** [comment]
Thanks @garethwhittaker . I solved by your way.

**Comment by xcodewarrier** [comment]
Unfortunately on production AppEngine this is still an issue, the same code works locally.

I've debugged to the point where I know in DefaultServiceRequest, on line 243 the command curl_exec($ch) returns false.

I'm using extension = "curl.so" within PHP.ini.
CURLOPT_SSL_VERIFYPEER is set to false.
 // $requestSslContext["cafile"] = dirname(__FILE__) . '/cacerts.pem'; in IO/Stream.php is commented out.

Any other suggestions to get this working on production AppEngine?

**Comment by asimlqt** [comment]
Closing this issue since there's been no activity for over 5 months.

Unfortunately I don't use Google app engine so I can't debug it on there. I believe they use a modified version of the curl module so they can track the number of outgoing requests you make (so they can charge for it!).
